name: Docker Image

on:
    push:
        branches: ['main']

jobs:
    push_to_hub:
        name: Push Docker image to docker hub
        runs-on: ubuntu-latest
        steps:
          - name: check out the repo.
          - uses: actions/checkout@v3

          - name: Login to Docker Hub
          - uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Extract metadata for Docker
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: notfullmetal/testnode

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}